import { createApp } from "vue";
import App from "./App.vue";
import "../src/assets/style.css";
import router from "./route";
import { createPinia } from "pinia";
import piniaPluginPersistedstate from "pinia-plugin-persistedstate";
const pinia = createPinia();
const app = createApp(App);
pinia.use(piniaPluginPersistedstate);
app.use(router);
app.use(pinia);
app.mount("#app");
